server:
  port:8087

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostGreSQLDialect
      jdbc:
        lob.non-contextual: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
